oldBuild/root/tgt/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^tgt/', include('tgt.foo.urls')),
    (r'^facebook/', include('django_facebook.urls')),
    (r'^accounts/', include('django_facebook.auth_urls')),
    (r'^accounts/', include('userena.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),


    (r'^api/saveGoodThing$','tgt.views.api_saveGoodThing'),
    (r'^api/delete','tgt.views.api_delete'),
    (r'^api/cheer','tgt.views.api_cheer'),
    (r'^api/uncheer','tgt.views.api_uncheer'),
    (r'^api/things','tgt.views.api_things'),
    (r'^api/saveSettings','tgt.views.api_saveSettings'),
    (r'^api/updateAuthToken','tgt.views.api_updateAuthToken'),

    (r'^user/([A-Za-z_0-9\.]*)/([0-9]+)$','tgt.views.gtview'),
    (r'^user/([A-Za-z_0-9\.]*)/$','tgt.views.index'),
    (r'^canvas/$', 'tgt.views.canvas'),
    (r'^privacy/$','tgt.views.privacy'),
    (r'^tos/$','tgt.views.tos'),
    (r'^favicon\.gif$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.gif'}),
    (r'^$', 'tgt.views.index'),
)

oldBuild/root/tgt/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django_facebook.api import get_facebook_graph
from time import sleep

stopwords = "a,about,across,after,all,almost,also,am,among,an,and,any,are,as,at,be,because,been,but,by,can,cannot,did,do,does,either,else,ever,every,for,from,get,got,had,has,have,he,her,hers,him,his,how,however,i,if,in,into,is,it,its,just,least,let,like,likely,may,me,might,most,must,my,neither,no,nor,not,of,off,often,on,only,or,other,our,own,rather,said,say,says,she,since,so,some,than,that,the,their,them,then,there,these,they,this,tis,to,too,twas,us,wants,was,we,were,what,when,where,which,while,who,whom,why,will,with,would,yet,you,your,yesterday,today".split(',')

class GoodThing(models.Model):
    goodThing = models.CharField("Good thing",max_length=200);
    reason = models.CharField("reason",max_length=200,blank=True,default=None)
    posted = models.DateTimeField(auto_now_add=True,editable=False)
    user = models.ForeignKey(User,editable=False)
    friends = models.CommaSeparatedIntegerField(max_length=128,blank=True,default=None)
    public = models.BooleanField(default=True,help_text="Make public within 3GT")
    wall = models.BooleanField(default=False,help_text="Post to Facebook NewsFeed")
    fbid = models.CharField(max_length=100,blank=True,default=None,editable=False)
    deleted = models.BooleanField(default=False,editable=False)
    
    def link(self):
        return "https://www.threegthings.net/user/"+self.user.username+"/"+str(self.id)
     
    def postFB(self,fb=None,useog=True):
        #new one with actions
        try:
            if useog:
                rdata = fb.set('me/threegoodthings:celebrate',good_thing=self.link(),tags=self.friends,scrape=True,explicitly_shared=True) 
            else:
                #if it's not set to use open graph, go ahead and use the old method.
                rdata = fb.set('me/feed', message=self.goodThing, link=self.link(), name=self.user.first_name + " celebrated a Good Thing!")
            self.fbid = rdata['id']
            self.save()
        except:
            pass
            
    def fbLink(self):
        if self.fbid == None: return False
        else:
            if len(self.fbid.split("_")) > 1:
                pid = self.fbid.split("_")[1]
                if self.user.username: return "http://facebook.com/%s/posts/%s"%(self.user.username,pid)
                else: return "http://www.facebook.com/permalink.php?id=%s&v=wall&story_fbid=%s"%(self.user.get_profile().facebook_id,pid)        
            else:
                if self.user.username: return "http://facebook.com/%s/activity/%s"%(self.user.username,self.fbid)
                else: return False

class Cheer(models.Model):
    user = models.ForeignKey(User)
    goodThing = models.ForeignKey(GoodThing)
    cheered = models.DateTimeField(auto_now_add=True)

class Settings(models.Model):
    user = models.ForeignKey(User)
    twitterHandle = models.CharField(max_length=24,blank=True,default=None)
    reminderDays = models.IntegerField(default=0)
    defaultFB = models.BooleanField(default=False)
    defaultPublic = models.BooleanField(default=True)

class WordClouds(models.Model):
        user = models.ForeignKey(User,editable=False,unique=True)
        rCloudPublic = models.TextField(blank=True)
        rCloudPrivate = models.TextField(blank=True)
        gtCloudPublic = models.TextField(blank=True)
        gtCloudPrivate = models.TextField(blank=True)
        
        def wordCloud(self,sources):
            words = []
            maxlength = 20
            
            for source in sources: words.extend(source.lower().split())
            from collections import defaultdict
            import operator
            d = defaultdict(int)
            for word in [w for w in words if not w in stopwords]: d[word] += 1
            counts = sorted(d.iteritems(), key=operator.itemgetter(1), reverse=True)
            if len(counts) > 0:
                del counts[maxlength:]
                minct = float(counts[-1][1])
                diff = max((counts[0][1]-minct),1.0)
                counts.sort()
                cloud = ["<span class='size%s'>%s</span>"%(int((wc[1]-minct)/diff*10),wc[0]) for wc in counts]
                
                return " ".join(cloud)
            return ''
            
        def updateClouds(self):
            import string
            
            tostrip="/\"?.\\<>,;:()*&^$#@!"
            punctuation = string.maketrans(tostrip," "*len(tostrip)).decode("latin-1")
            
            goodThings = GoodThing.objects.filter(deleted=False).filter(user=self.user)
            self.gtCloudPrivate = self.wordCloud([gt.goodThing.translate(punctuation) for gt in goodThings])
            reasons = [gt.reason.translate(punctuation) for gt in goodThings if gt.reason is not None]
            if len(reasons) > 0: self.rCloudPrivate = self.wordCloud(reasons)
            else: self.rCloudPrivate = ""
            
            goodThings = goodThings.filter(public=True)
            self.gtCloudPublic = self.wordCloud([gt.goodThing.translate(punctuation) for gt in goodThings])
            #self.rCloudPublic = self.wordCloud([gt.reason.translate(punctuation) for gt in goodThings])
            self.rCloudPublic = ""
        
            self.save()
            
            

oldBuild/root/tgt/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseForbidden
from django.db.models import Q
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_exempt
from django_facebook.canvas import generate_oauth_url
from django.shortcuts import render_to_response
from django import forms
from models import GoodThing, WordClouds, Cheer, Settings
from django.contrib.auth.models import User
from django.contrib.auth import logout
import django_facebook
from django.core.paginator import Paginator, InvalidPage
from django.utils import timezone
#import urllib, urllib2
#from tasks import scrapeGoodThing

### FORMS GO HERE

class GoodThingForm(forms.ModelForm):
    class Meta:
        model = GoodThing
        widgets = {'goodThing':forms.Textarea(),
                   'reason':forms.Textarea(),
                  }
                  
class SettingsForm(forms.Form):
    reminders = forms.BooleanField(required=False)
    reminderDays = forms.ChoiceField(choices=(('1','1'),('2','2'),('3','3'),('4','4'),('5','5')))
    defaultFB = forms.BooleanField(required=False)
    defaultPublic = forms.BooleanField(required=False)
    
### API STUFF GOES HERE

def api_things(request):
    t = loader.get_template('thingsjson.json')
    page = request.GET.get("page",1)

    #objectlist will eventually depend on what they are asking for. but for now...
    specificUser = request.GET.get("uid",False)
    if specificUser:
         gtlist = GoodThing.objects.filter(deleted=False).order_by('-posted').filter(public=1).filter(user=specificUser)
    elif request.user.is_authenticated():
        gtlist = GoodThing.objects.filter(deleted=False).order_by('-posted').filter(Q(public=1)|Q(user=request.user))
    else:
         gtlist = GoodThing.objects.filter(deleted=False).order_by('-posted').filter(public=1)

    paginator = Paginator(gtlist,30)
    page_obj = paginator.page(page)
    c = RequestContext(request,{
            "object_list": page_obj.object_list,
            "page": page_obj
            })
    return HttpResponse(t.render(c))

def api_delete(request):
    if request.user.is_authenticated():
        gt = GoodThing.objects.get(id=request.POST['gtid'])
        if gt.user == request.user:
            gt.deleted = True
            gt.save()
            
            try:
               wc = WordClouds.objects.get(user=request.user)
            except:
               wc = WordClouds()
               wc.user = request.user
           
            wc.updateClouds()
            return HttpResponse("")

    return HttpResponseForbidden()

def api_cheer(request):
    if request.user.is_authenticated():
        gt = GoodThing.objects.get(id=request.POST['gtid'])
        cheer = Cheer()
        cheer.user = request.user
        cheer.goodThing = gt
        cheer.save()
        
        return HttpResponse(str(gt.id))

    return HttpResponseForbidden()

def api_uncheer(request):
    if request.user.is_authenticated():
        gt = GoodThing.objects.get(id=request.POST['gtid'])
        cheers = Cheer.objects.all().filter(goodThing=gt).filter(user=request.user)
        for cheer in cheers: cheer.delete()
        return HttpResponse(str(gt.id))

    return HttpResponseForbidden()

def api_saveGoodThing(request):
    if request.user.is_authenticated():
        fb = django_facebook.api.get_persistent_graph(request)
        
        gt = GoodThing()
        gt.user = request.user
        gt = GoodThingForm(request.POST,instance=gt)
        gt.save()
        
        #if gt.instance.public:
            #vals = {'id':gt.instance.link(),'scrape':'true'}
            #data = urllib.urlencode(vals)
            #req = urllib2.Request("https://graph.facebook.com", data)
            #response = urllib2.urlopen(req)
            #scrapeGoodThing.delay(gt.instance.id)
                        
        try:
            wc = WordClouds.objects.get(user=request.user)
        except:
            wc = WordClouds()
            wc.user = request.user
        wc.updateClouds()
        
        if gt.instance.wall:
            if not gt.instance.public:
                gt.instance.postFB(fb,useog=False)
            else:
                gt.instance.postFB(fb)
        
        t =  loader.get_template('thingjson.json')
        c = RequestContext(request,{'obj':gt.instance})
        return HttpResponse(t.render(c))
    else:
        return HttpResponseForbidden()

def api_saveSettings(request):
    if request.user.is_authenticated():
        try:
            settings = Settings.objects.get(user=request.user)
        except:
            settings = Settings()
            settings.user = request.user
        
        form = SettingsForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            if form.cleaned_data['reminders']:
                settings.reminderDays = form.cleaned_data['reminderDays']
            else:
                settings.reminderDays = 0
            settings.defaultFB = form.cleaned_data['defaultFB']
            settings.defaultPublic = form.cleaned_data['defaultPublic']
            settings.save()
            return HttpResponse("Saved.") 
        else:
            return HttpResponse("Something broke.")
    else:
        return HttpResponseForbidden()

def api_updateAuthToken(request):
    if request.user.is_authenticated():
        profile = request.user.get_profile()
        access_token = request.POST['accessToken']
        profile.access_token = access_token
        profile.save()
        return HttpResponse("Updated.") 
        
    return HttpResponseForbidden()


### ACTUAL PAGES GO HERE
def index(request,username=None,inFb=False):

    if request.user.is_authenticated() or username is not None:
        
        import datetime
        if request.user.is_authenticated(): gtForm = GoodThingForm()
        else: gtForm = None
        
        #get some stats for the user
        if username is not None: 
            try:
                statsuser = User.objects.get(username=username)
            except:
                return HttpResponseNotFound("User not found.")
        else:
            #someone is looking at their homepage. let's make sure we have a current token.
            fb = django_facebook.api.get_persistent_graph(request)
            try: 
                trial = fb.get('me/friends')
            except:
                #no valid oauth token, get them to log in again.
                logout(request) 
                t = loader.get_template('index.html')
                c = RequestContext(request,{'inFb':inFb})
                return HttpResponse(t.render(c))
            
            statsuser = request.user
            #okay, so we should add some settings
            try:
                settings = Settings.objects.select_related().get(user=request.user)
            except:
                settings = Settings()
                settings.user = request.user
                settings.save()
            
            initial={'defaultFB': settings.defaultFB, 'defaultPublic': settings.defaultPublic}
            if settings.reminderDays != 0:
                initial['reminders']=True
                initial['reminderDays']=settings.reminderDays
            else: 
                initial['reminders'] = False;
            
            settingsForm = SettingsForm(initial=initial)
            
        gtcount = GoodThing.objects.filter(user=statsuser).filter(deleted=False).count()
        perday = float(gtcount)/max(((timezone.now() - statsuser.date_joined).days),1)
        
        if gtcount > 0:
            try:
                wc = WordClouds.objects.get(user=statsuser)
            except:
                wc = WordClouds()
                wc.user = statsuser
                wc.updateClouds()
        else: wc = None
        
        t = loader.get_template('myview.html')
        cdict = {'form':gtForm,'gtcount':gtcount,'perday':perday,'wc':wc,'inFb':inFb}
        if username is not None: cdict['viewuser'] = statsuser
        else:
            cdict['settings'] = settings
            cdict['settingsform'] = settingsForm
        
        c = RequestContext(request,cdict)
        
        return HttpResponse(t.render(c))
    #and if not, let's get them logged in
    
    else:
        #return HttpResponse(request.__str__())
        t = loader.get_template('index.html')
        c = RequestContext(request,{'inFb':inFb})
        return HttpResponse(t.render(c))

def privacy(request):
    t = loader.get_template('privacy.html')
    c = RequestContext(request,{})
    return HttpResponse(t.render(c))

def tos(request):
    t = loader.get_template('tos.html')
    c = RequestContext(request,{})
    return HttpResponse(t.render(c))
    
def gtview(request,username,gtid,inFb=False):
    try:
        gt = GoodThing.objects.select_related('user').get(id=gtid)
        
        if gt.user.username == username:
            if not gt.public and gt.user != request.user: return HttpResponseForbidden("Sorry, you don't have permission to view this content.")
        
            friendshtml = None
            if gt.friends:
                fb = django_facebook.api.get_facebook_graph(request)
                friendnames = []
                for friend in gt.friends.split(','):
                    try:
                        friendnames.append(fb.get(friend,fields='name')['name'])
                    except: 
                        pass
                friendshtml=", ".join(friendnames)
        
            t = loader.get_template('goodthing.html')
            c = RequestContext(request,{'gt':gt,'inFb':inFb,'initialCheer':False,'friends':friendshtml})

            if request.user.is_authenticated():
                try:
                    for cheer in gt.cheer_set.filter(user=request.user): c['initialCheer'] = True
                except:
                    pass
            
            return HttpResponse(t.render(c))

oldBuild/root/tgt/templates/myview.html
{% extends "base.html" %}

{% block title %}{% if viewuser %}{{viewuser.first_name}} {{viewuser.last_name}} :: {% endif %}{% endblock %}

{% block extracssjs %}
<script src="https://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js" type="text/javascript"></script>
{% if not viewuser %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.tokeninput.min.js"></script>
{% endif %}
<script src="{{ STATIC_URL }}js/tgthelpers.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/tgtfeed.js" type="text/javascript"></script>
<script type="text/javascript">
	var {% if request.user.is_authenticated%}uid = {{request.user.id}},{%endif%}
	 	csrfmiddlewaretoken = '{{csrf_token}}',
		feedSelector = "{%if viewuser%}&uid={{viewuser.id}}{%endif%}";


	$(document).ready(function(){
		tgtDocumentReady();
		//$('.twipabled').tooltip();
		if (window.location != window.parent.location){$('head').append('<link href="/static/css/tgtfb.css" type="text/css" rel="stylesheet" media="all" />');};
		
	    {% if not viewuser %}
		$('#settingslink').on('click',function(){$('#settings').toggle('fast')});


		$('#id_reason, #tagfriends, #buttons, #lock, #privatereason').hide();
		//show reason bar and buttons when the good thing post bar is clicked into           
		$('#id_goodThing').click(function() {
	        $('#id_reason,#tagfr,#buttons,#lock,#privatereason,#tagfriends').show();
		});

		$('#gtForm').submit(function(){
			$('#postbtn').attr('disabled','disabled');
			$.post("/api/saveGoodThing", $("#gtForm").serialize(), function(returnData){
				$('#gtForm')[0].reset();
				var item = $.parseJSON(returnData);
				renderGoodThing(item).prependTo("#goodThingsList");
				$("#id_friends").tokenInput("clear");
				$('#postbtn').removeAttr('disabled');
				$('#gtcount').html(Number($('#gtcount').html())+1);
			});
			return false;
		});
		
		$('#settingsForm').submit(function(){
			$('#savesettings').attr('disabled','disabled');
			$.post("/api/saveSettings", $("#settingsForm").serialize(), function(returnData){
				$('#settingsForm')[0].reset();
				$('#savesettings').removeAttr('disabled');
				$('#settings').toggle('fast');
			});
			return false;
		});
	    {% endif %}
	});
</script>
{% if not viewuser %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/token-input-facebook.css" type="text/css" />
{% endif %}
{% if viewuser = request.user %}
<style type="text/css">
	.cheerlink{display:none;}
</style>
{% endif %}
{% endblock %}

{% block content %}
     <div class="content">
	
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
	
		<div class="row">
 	   <div id="you" class="span4">
 	     <div class="leftbox">
 	     {% if not viewuser %}<div id="selfimg"><img src="http://graph.facebook.com/{{ request.user.get_profile.facebook_id }}/picture?type=square" alt="{{request.user.first_name}} {{request.user.last_name}}"/></div><h2 id="name">{{request.user.first_name}} {{request.user.last_name}}</h2>
 		 <div><a  class="profilelink" id="settingslink" href="#">settings</a></div>
 		 {% else %}
 	     <div id="selfimg"><img src="http://graph.facebook.com/{{ viewuser.get_profile.facebook_id }}/picture?type=square" alt="{{viewuser.first_name}} {{viewuser.last_name}}"/></div><h2 id="name">{{viewuser.first_name}} {{viewuser.last_name}}</h2>
 		 <div><a class="profilelink" href="/">home</a></div>
 		 {% endif %}
 	     <div id="stats"><span class="stat"><span class="number" id="gtcount">{{gtcount}}</span> Good Things</span><span class="stat"><span class="number">{{perday|floatformat}}</span> Per Day</span></div>
 		  {% if not viewuser %}
 		 <div id="settings">
 			 <form name="settingsForm" id="settingsForm" method="post" action="">{% csrf_token %}
 			 <h3>Settings</h3>
 			 <table>
 			 <tr><td>{{settingsform.reminders}}</td><td>Email reminders after {{settingsform.reminderDays}} days without posting.</td></tr>
 			 <tr><th colspan="2">Posting Defaults</th></tr>
 			 <tr><td>{{settingsform.defaultPublic}}</td><td><label for="id_defaultPublic">Post publicly on 3GT</label></td></tr>
 			 <tr><td>{{settingsform.defaultFB}}</td><td><label for="id_defaultFB">Post to Facebook</label></td></tr>
 			 <tr><td></td><td><button id="savesettings" class="btn">Save</button></td>
 			 </table>
 			 </form>
 		 </div>
 		 {% endif %}
 	     </div>
 		 {% if wc %}
 	     <div class="leftbox">
 	      {% if not viewuser %}<h3>Your top Good Thing Words</h3> {{wc.gtCloudPrivate|safe}}{% else %}<h3>{{viewuser.first_name}}'s top Good Thing Words</h3> {{wc.gtCloudPublic|safe}}{% endif %}
 	     </div>
 	     {% if not viewuser %}
 			 <div class="leftbox">
 				<h3>Your top Reason Words</h3>
 			   {{wc.rCloudPrivate|safe}}
 			 </div>
 			 {% endif %}
 		 {% else %}
 			 {% if not viewuser %}
 			 <div class="leftbox">
 			 <h2>Welcome! Let's get started.</h2>
 			<p>To get started, just record a good thing and why it happened using the form to the right.</p>
 			<p>You can change where each good thing is shared (or not shared) from the posting form, and you can change the defaults using the settings option above.</p>
 			 </div>
 			 {% endif %}
 		 {% endif %}

 	    </div>
		
	  <div id="feed" class="span7">
	    {% if viewuser = request.user %}<p><em>This is how your profile looks to others. Go <a href="/">home.</a></em></p>{% endif %}
	    {% if not viewuser %}
		
		<div id="my_good_thing" class="media-list">
			<div class="media" style="overflow:visible; padding-bottom:0px">
			<a class="pull-left" href="#" style="margin-right:0px"><img src="http://graph.facebook.com/{{ request.user.get_profile.facebook_id }}/picture?type=square" alt="{{request.user.first_name}} {{request.user.last_name}}" class="media-object"/></a>
			<a class="pull-left" href="#" style="margin-left:2px; padding-top:20px"><i class="right-caret"></i></a>
			<div class="media-body" style="overflow:inherit; margin-left:60px" >
				<div class="well well-small">
					<div class="input-append" style="padding-top:15px; padding-bottom:0px; padding-left:10px"> 
						   <form id="gtForm" name="gtForm" method="post" action="">{% csrf_token %}
							<fieldset>
								<div><input  class="span6" id="id_goodThing" name="goodThing" type="text" placeholder="What was the good thing?" /></div>						
								<div><input  class="span6" id="id_reason" name="reason" style="display:none" type="text" placeholder="Why did it happen? (Your reason is always private)" /><i id="lock" class="icon-lock"></i></div>
								<div id="tagfriends" class="span6" style="margin-left:0px;"><input class="span6" id="id_friends" name="friends" type="text" placeholder="Who were you with?" /></div>

								<div id="buttons" class="span6">
									<label class="checkbox inline" for="id_public"><input type="checkbox" name="public" id="id_public" {% if settings.defaultPublic %}checked="checked"{% endif %}/>Post to 3GT</label> <label class="checkbox inline" for="id_wall"><input type="checkbox" name="wall" id="id_wall" {% if settings.defaultFB %}checked="checked"{% endif %}/>Public on Facebook</label>
									<div class="pull-right" style="padding-right:20px;">
									<button class="btn btn-primary" style="margin-top:10px" id="postbtn">Post</button></div>
								</div>
							</fieldset>
							</form>
						</div>
					</div>
				</div>	
			</div>		
		</div>		
		
		

	  {% endif %}
	  	<ul class="media-list" id="goodThingsList"></ul>
	  <div id="load-anchor"></div>
	   </div>
 		</div>
{% endblock %}

{% block afterjs %}
{% if not viewuser %}
<div id="fb-root"></div>
<script src="/static/js/facebook.js" type="text/javascript"></script>
<script>
    facebookAppId = '119352832576';
    facebookDefaultScope = ["email", "user_about_me", "user_birthday", "user_website"];
    staticUrl = '/static/';
	function facebookJSLoaded(){
		FB.init({appId: facebookAppId, status: false, cookie: true, xfbml: true, oauth: true});
		FB.getLoginStatus(function(response) {
			if (response.status === 'connected') {
				var accessToken = response.authResponse.accessToken;
				FB.api('/me/friends?access_token='+accessToken, function(response) {
					$("#id_friends").tokenInput(response.data, {
                  	  theme: "facebook",
					  preventDuplicates: true,
					  hintText: "Start typing a friend's name",
				  });	
				});
				
		  	}else{$("#tagfriends").hide()};
	  	});
  	};
    window.fbAsyncInit = facebookJSLoaded;
    F = new facebookClass(facebookAppId);
    F.load();
</script>
{% else %}
{% include 'django_facebook/_facebook_js.html' %}
{% endif %}
{% endblock %}

oldBuild/root/tgt/templates/privacy.html
{% extends "base.html" %}

{% block title %}Privacy Policy :: {% endblock %}

{% block extracssjs %}
<style type="text/css">#theGoodThing{margin: 0em;font-size:1em;}</style>
{% endblock %}

{% block content %}
<div class="content"><div id='theGoodThing'>
<h2>Privacy Policy</h2>
<p>3GT is a research application developed at the University of Michigan's School of Information. We collect and use certain information in order for the application to function and to support our research.</p>
<h3>What we collect</h3>
<p>We collect the following information from your Facebook profile:</p>
<ul>
<li>name and Facebook username</li>
<li>email address</li>
<li>an offline access token to post to Facebook on your behalf</li>
<li>your birthdate</li>
</ul>

<p>Within the 3GT application, we collect:</p>
<ul>
<li>good things and reasons you post</li>
<li>comments, cheers, and other actions you take on your own or others' good things</li>
</ul>

<p>We may also access, but do not store, your Facebook friends list.</p>

<h3>What we do with this information</h3>
<p>We require this information for the 3GT application to function, including for the follwoing reasons:</p>
<ul>
<li>Allowing you to post, access, and view your Good Things</li>
<li>Posting Good Things, as you request and specify, to your Facebook News Feed</li>
</ul>

<p>We also require this information for research purposes, including contacting you from time to time to ask you about your experiences using the application. We may report on your use behavior in aggregate, and may anonymously use some of your Good Things and Reasons when we report on our research. You, or anyone you post about, will not be identified in any way in these reports.</p>

<p>Other than functions of 3GT described above and these anonymous or aggregate research reports, we will not sell, distribute, or lease your personal information to third parties unless we are required by law to do so.</p>
</div>
</div></div>
{% endblock %}